# Generated by Django 2.2 on 2020-05-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_auto_20200314_1619'),
        ('accounts', '0004_remove_profile_bio'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=150)),
                ('course_image', models.ImageField(default='course/default.png', upload_to='course/%Y/%m/%d/')),
                ('course_credit', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='programs.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='session.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='student_courses', to='course.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_student_course', to='session.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluateStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255)),
                ('question2', models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255)),
                ('question3', models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255)),
                ('rating', models.CharField(choices=[('1', 'Poor'), ('2', 'Average'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], default='3', max_length=150)),
                ('review', models.TextField(default='Review')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_evaluate', to='course.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_evaluate', to='session.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluate', to='accounts.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluate', to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='course.Course')),
                ('teachers', models.ManyToManyField(related_name='teacher_courses', to='accounts.Teacher')),
            ],
        ),
    ]
