# Generated by Django 2.2 on 2020-02-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        ('programs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=150)),
                ('course_image', models.ImageField(upload_to='course/%Y/%m/%d/')),
                ('course_credit', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='programs.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='session.Semester')),
                ('teacher', models.ManyToManyField(related_name='teacher_courses', to='accounts.Teacher')),
            ],
        ),
    ]
