# Generated by Django 2.2 on 2020-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='CSE101', max_length=150),
            preserve_default=False,
        ),
    ]
