# Generated by Django 2.2 on 2020-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200307_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatestudent',
            name='review',
            field=models.TextField(default='Review'),
        ),
    ]
