# Generated by Django 2.2 on 2020-03-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_studentcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignteacher',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
