# Generated by Django 2.2 on 2020-03-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200304_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
    ]
