# Generated by Django 2.2 on 2020-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200307_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question',
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question3',
            field=models.CharField(default='', max_length=255),
        ),
    ]
