# Generated by Django 2.2 on 2020-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_studentcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='courses',
            field=models.ManyToManyField(related_name='student_courses', to='course.Course'),
        ),
    ]
