# Generated by Django 2.2 on 2020-03-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200307_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatestudent',
            old_name='question1',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question3',
        ),
    ]
