# Generated by Django 2.2 on 2020-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200307_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatestudent',
            name='question',
            field=models.CharField(choices=[('JAN', 'January'), ('JAN', 'February'), ('JAN', 'March')], default='JAN', max_length=255),
        ),
    ]
