# Generated by Django 2.2 on 2020-03-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('course', '0007_studentcourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='semster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester_student_course', to='session.Semester'),
            preserve_default=False,
        ),
    ]
