# Generated by Django 2.2 on 2020-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200307_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatestudent',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
