# Generated by Django 2.2 on 2020-03-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_studentcourse_semster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='semster',
            new_name='semester',
        ),
    ]
