# Generated by Django 2.2 on 2020-03-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200308_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatestudent',
            old_name='question1',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question3',
        ),
    ]
