# Generated by Django 2.2 on 2020-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200308_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatestudent',
            name='question',
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question1',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question2',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluatestudent',
            name='question3',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'Average'), ('3', 'No')], default='2', max_length=255),
        ),
    ]
