# Generated by Django 2.2 on 2020-03-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('course', '0011_auto_20200308_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatestudent',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester_evaluate', to='session.Semester'),
            preserve_default=False,
        ),
    ]
