# Generated by Django 2.2 on 2020-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_evaluatestudent_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course/default.png', upload_to='course/%Y/%m/%d/'),
        ),
    ]
