# Generated by Django 2.2 on 2020-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=50)),
                ('session_year', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
