# Generated by Django 2.2 on 2020-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
                ('semester_year', models.CharField(max_length=50)),
                ('semester_full_name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
