# Generated by Django 2.2 on 2020-03-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_city_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
