# Generated by Django 2.2 on 2020-03-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200314_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_weather', to=settings.AUTH_USER_MODEL),
        ),
    ]
