# Generated by Django 2.2 on 2020-03-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200314_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
