# Generated by Django 2.2 on 2020-03-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Program'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=150, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_department', to='programs.Faculty', verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=150, verbose_name='Department Name'),
        ),
    ]
