# Generated by Django 2.2 on 2020-02-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200225_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_department', to='programs.Faculty')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
